const positions = {
    "white_pawn1":{
        "position":{
            "x":0,
            "y":6
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":0,
                    "y":6
                }
            }
        ]
    },
    "white_pawn2":{
        "position":{
            "x":1,
            "y":6
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":1,
                    "y":6
                }
            }
        ]
    },
    "white_pawn3":{
        "position":{
            "x":2,
            "y":6
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":2,
                    "y":6
                }
            }
        ]
    },
    "white_pawn4":{
        "position":{
            "x":3,
            "y":6
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":3,
                    "y":6
                }
            }
        ]
    },
    "white_pawn5":{
        "position":{
            "x":4,
            "y":6
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":4,
                    "y":6
                }
            }
        ]
    },
    "white_pawn6":{
        "position":{
            "x":5,
            "y":6
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":5,
                    "y":6
                }
            }
        ]
    },
    "white_pawn7":{
        "position":{
            "x":6,
            "y":6
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":0,
                    "y":6
                }
            }
        ]
    },
    "white_pawn8":{
        "position":{
            "x":7,
            "y":6
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":7,
                    "y":6
                }
            }
        ]
    },
    "black_pawn1":{
        "position":{
            "x":0,
            "y":1
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":0,
                    "y":1
                }
            }
        ]
    },
    "black_pawn2":{
        "position":{
            "x":1,
            "y":1
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":1,
                    "y":1
                }
            }
        ]
    },
    "black_pawn3":{
        "position":{
            "x":2,
            "y":1
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":2,
                    "y":1
                }
            }
        ]
    },
    "black_pawn4":{
        "position":{
            "x":3,
            "y":1
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":3,
                    "y":1
                }
            }
        ]
    },
    "black_pawn5":{
        "position":{
            "x":4,
            "y":1
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":4,
                    "y":1
                }
            }
        ]
    },
    "black_pawn6":{
        "position":{
            "x":5,
            "y":1
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":5,
                    "y":1
                }
            }
        ]
    },
    "black_pawn7":{
        "position":{
            "x":6,
            "y":1
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":6,
                    "y":1
                }
            }
        ]
    },
    "black_pawn8":{
        "position":{
            "x":7,
            "y":1
        },
        "allowed":2,
        "past":[
            {
                "previous":{
                    "x":7,
                    "y":1
                }
            }
        ]
    },
    "black_horse1":{
        "position":{
            "x":1,
            "y":0
        },
        "allowed":4,
        "past":[
            {
                "previous":{
                    "x":1,
                    "y":0
                }
            }
        ]
    },
    "black_horse2":{
        "position":{
            "x":6,
            "y":0
        },
        "allowed":4,
        "past":[
            {
                "previous":{
                    "x":6,
                    "y":0
                }
            }
        ]
    },
    "white_horse1":{
        "position":{
            "x":1,
            "y":7
        },
        "allowed":4,
        "past":[
            {
                "previous":{
                    "x":1,
                    "y":7
                }
            }
        ]
    },
    "white_horse2":{
        "position":{
            "x":6,
            "y":7
        },
        "allowed":4,
        "past":[
            {
                "previous":{
                    "x":6,
                    "y":7
                }
            }
        ]
    },
    "black_elephant1":{
        "position":{
            "x":0,
            "y":0
        },
        "allowed":14,
        "past":[
            {
                "previous":{
                    "x":0,
                    "y":0
                }
            }
        ]
    },
    "black_elephant2":{
        "position":{
            "x":7,
            "y":0
        },
        "allowed":14,
        "past":[
            {
                "previous":{
                    "x":7,
                    "y":0
                }
            }
        ]
    },
    "white_elephant1":{
        "position":{
            "x":7,
            "y":7
        },
        "allowed":14,
        "past":[
            {
                "previous":{
                    "x":7,
                    "y":7
                }
            }
        ]
    },
    "white_elephant2":{
        "position":{
            "x":0,
            "y":7
        },
        "allowed":14,
        "past":[
            {
                "previous":{
                    "x":0,
                    "y":7
                }
            }
        ]
    },
    "black_knight1":{
        "position":{
            "x":2,
            "y":0
        },
        "allowed":28,
        "past":[
            {
                "previous":{
                    "x":2,
                    "y":0
                }
            }
        ]
    },
    "black_knight2":{
        "position":{
            "x":5,
            "y":0
        },
        "allowed":28,
        "past":[
            {
                "previous":{
                    "x":5,
                    "y":0
                }
            }
        ]
    },
    "white_knight1":{
        "position":{
            "x":2,
            "y":7
        },
        "allowed":28,
        "past":[
            {
                "previous":{
                    "x":2,
                    "y":7
                }
            }
        ]
    },
    "white_knight2":{
        "position":{
            "x":5,
            "y":7
        },
        "allowed":28,
        "past":[
            {
                "previous":{
                    "x":5,
                    "y":7
                }
            }
        ]
    },
    "black_queen":{
        "position":{
            "x":3,
            "y":0
        },
        "allowed":42,
        "past":[
            {
                "previous":{
                    "x":3,
                    "y":0
                }
            }
        ]
    },
    "black_king":{
        "position":{
            "x":4,
            "y":0
        },
        "allowed":4,
        "past":[
            {
                "previous":{
                    "x":4,
                    "y":0
                }
            }
        ]
    },
    "white_queen":{
        "position":{
            "x":3,
            "y":7
        },
        "allowed":42,
        "past":[
            {
                "previous":{
                    "x":3,
                    "y":7
                }
            }
        ]
    },
    "white_king":{
        "position":{
            "x":4,
            "y":7
        },
        "allowed":4,
        "past":[
            {
                "previous":{
                    "x":4,
                    "y":7
                }
            }
        ]
    },


    
}